# Site settings
title: Proceed.to >
tag_text: Proceed.to > # Media, writing, podcasting, and more
description: Media and content services — from building in-house editorial teams to creating content strategies
url: "https://transcendent-dodol-2f741f.netlify.app" # base URL for your site ie. "https://www.example.com"
baseurl: "" # subpath for base of site, leave blank if hosting at root

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
